name: Backend Integration (CI)

on: 
    workflow_dispatch:
    pull_request:
        branches:
            - main

env:
    PYTHON_VERSION: '3.10'
    # SRC_DIR - path to the backend root src folder
    SRC_DIR: '${{ github.workspace }}/src/backend/'

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
                
            - name: Setup Python ${{env.PYTHON_VERSION}}
              uses: actions/setup-python@v4
              with:
                python-version: ${{env.PYTHON_VERSION}}
            
            - name: Install dependencies
              run: cd ${{env.SRC_DIR}} && pipenv install --dev
            - name: Run linter
              run: cd ${{env.SRC_DIR}} && pipenv run lint
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
                
            - name: Setup Python ${{env.PYTHON_VERSION}}
              uses: actions/setup-python@v4
              with:
                python-version: ${{env.PYTHON_VERSION}}
                cache: 'pipenv'
            
            - name: Install dependencies
              run: cd ${{env.SRC_DIR}} && pipenv install --dev
            - name: Run linter
              run: cd ${{env.SRC_DIR}} && pipenv run test
    
    build:
        needs: [lint, test]
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            
            - name: Setup Python ${{env.PYTHON_VERSION}}
              uses: actions/setup-python@v4
              with:
                python-version: ${{env.PYTHON_VERSION}}
                cache: 'pipenv'
            
            - name: Install dependencies
              run: cd ${{env.SRC_DIR}} && pipenv install --dev
            - name: Run linter
              run: cd ${{env.SRC_DIR}} && pipenv run test
            
            - name: Login to Amazon ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v2
            
            - name: Build Docker image
              env:
                REGISTRY: ${{ steps.login-ecr.outputs.registry }}
                REPOSITORY: backend
                IMAGE_TAG: ${{ github.sha }}
              run: |
                  cd ${{env.SRC_DIR}}
                  docker build --tag=$REGISTRY/$REPOSITORY:$IMAGE_TAG .