name: Backend Deployment (CD)

on: 
    workflow_dispatch:
    pull_request:
        branches:
            - main

env:
    PYTHON_VERSION: '3.10'
    # path to the backend root folder
    SRC_DIR: '${{ github.workspace }}/src/backend/'
    ECR_REPO: '815822840554.dkr.ecr.us-west-2.amazonaws.com/backend'

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
                
            - name: Setup Python ${{env.PYTHON_VERSION}}
              uses: actions/setup-python@v4
              with:
                python-version: ${{env.PYTHON_VERSION}}
            # TODO: Perform a cache action to restore cache before deps install.
            - name: Install dependencies
              run: cd ${{env.SRC_DIR}} && pipenv install
            - name: Run linter
              run: cd ${{env.SRC_DIR}} && pipenv run lint
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
                
            - name: Setup Python ${{env.PYTHON_VERSION}}
              uses: actions/setup-python@v4
              with:
                python-version: ${{env.PYTHON_VERSION}}
            # TODO: Perform a cache action to restore cache before deps install.
            - name: Install dependencies
              run: cd ${{env.SRC_DIR}} && pipenv install
            - name: Run linter
              run: cd ${{env.SRC_DIR}} && pipenv run test
    
    build:
        needs: [lint, test]
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            
            - name: Debug output
              run: echo 'We made it here'