name: Frontend Integration (CI)

on: 
    workflow_dispatch:
    pull_request:
        branches:
            - main

env:
    NODE_VERSION: 'latest'
    # path to the frontend root folder
    SRC_DIR: '${{ github.workspace }}/src/frontend/'

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
                
            - name: Setup NodeJS ${{env.NODE_VERSION}}
              uses: actions/setup-node@v3
              with:
                node-version: ${{env.NODE_VERSION}}
                cache: 'npm'
            
            # TODO: Perform a cache action to restore cache before deps install.
            - name: Install dependencies
              run: cd ${{env.SRC_DIR}} && npm ci
            
            - name: Run linter
              run: cd ${{env.SRC_DIR}} && npm run lint
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
                
            - name: Use NodeJS ${{env.NODE_VERSION}}
              uses: actions/setup-node@v3
              with:
                node-version: ${{env.NODE_VERSION}}
            # TODO: Perform a cache action to restore cache before deps install.
            - name: Install dependencies
              run: cd ${{env.SRC_DIR}} && npm ci
            
            - name: Build
              run: cd ${{env.SRC_DIR}} && npm test
    
    build:
        needs: [lint, test]
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            
            - name: Use NodeJS ${{env.NODE_VERSION}}
              uses: actions/setup-node@v3
              with:
                node-version: ${{env.NODE_VERSION}}
                cache: 'npm'
            
            - name: Install dependencies
              run: cd ${{env.SRC_DIR}} && npm ci
            
            - name: Build
              run: cd ${{env.SRC_DIR}} && npm run build